## To modify by developper(s) of the plugin

[plugin-info]
SHORT_PLUGIN_NAME = 'crystal_technology'  #to be modified, for instance daqmx then rename the module name:
# (pymodaq_plugins_crystal_technology become pymodaq_plugins_daqmx for instance)

package-url = 'https://github.com/PyMoDAQ/pymodaq_plugins_crystal_technology' #to modify
description = 'some word about your plugin'

author = 'Sebastien J. Weber'
author-email = 'sebastien.weber@cemes.fr'
license = 'MIT'

[plugin-install]
#packages required for your plugin:
packages-required = ['portion'] #portion is for numbers intervals
